### ISSUE TITLE
Allow naenae functionality to be reachable through `wip` entrypoint

### ISSUE THREAD

**Issue by Alxandr** [bitjson/wip#4]
So, us programmers (read I) am fairly bad at remembering obscure application names (or just names in general). `wip` is easy, first of all because I've used it for years, and second of all cause I use it all the time, however I keep having to find this repo to lookup what `naenae` is called which is somewhat counterproductive. I suggest allowing `naenae` to be invoked by a command-line switch (or similar) to `wip`. My best suggestion currently is something akin to `wip done` or maybe going with what is known to gitters `wip commit` is forwarded to `naenae` automatically.

**Comment by bitjson** [comment]
Hey @Alxandr, this is a great idea! I'll try to implement something this evening. 

Does Windows allow tab completion for `wip` and `naenae` currently? On *nix I type `nae`+[tab] and `naenae` is autocompleted.

**Comment by Alxandr** [comment]
Not tried it. I tend to only use tab completion on file names cause windows trends to add .exe

**Comment by bitjson** [comment]
https://github.com/bitjson/wip/commit/6a24b6e8408cbce5c7aea3149871b5885afd7662

**Comment by bitjson** [comment]
@Alxandr – I added some helpful messages for when users run wip `commit`, `done`, `finish`, and `ok`, as well as when `wip` is run without changes to commit. (After a little thought, since `naenae` is potentially destructive if run before the user is ready, I think it's best for users to clarify their intentions rather than assuming they meant to `naenae`.)

There's also help information at `wip help` (and if an argument is not recognized). And finally, `man wip` also references `naenae`. So hopefully that should make it easier to remember!
